### PR TITLE
Add 0 h_calls back in, since Optim is now tagged

### PR DESCRIPTION
**Pull request by pkofod**
Should fix (let's see test output) https://github.com/JuliaOpt/Optim.jl/issues/316

### CODE REVIEW

**Comment by pkofod** [comment]
nightlies fail due to macro hygene, but even with that fixed it fails due to weird bug where you go out of bounds when using parametric arrays in types.

**Comment by pkofod** [comment]
Tests should pass now; rerun?

**Comment by blakejohnson** [comment]
I restarted Travis.

**Comment by pkofod** [comment]
And I bumped the version requirement. Seems to be :+1:

**Pull request merged**
