### PR TITLE
result.minimum -> result.minimizer

### PR DESCRIPTION
**Pull request by jw3126**
propagate upstream renaming

### CODE REVIEW

**Comment by blakejohnson** [comment]
Do we need to wait for a version to propagate or something?

**Comment by jw3126** [comment]
You are right, I was using `Optim` master locally.

**Comment by blakejohnson** [comment]
Could you ping this PR when there is a new `Optim.jl` release? We'll also want to update the `REQUIRE` file accordingly.

**Comment by jw3126** [comment]
Do you still want to support julia 0.3? If not, this can work with both master and current release of Optim.

**Comment by blakejohnson** [comment]
No, I'd be happy to drop support for Julia 0.3.

**Comment by jw3126** [comment]
Okay this is ready!

**Comment by blakejohnson** [comment]
I guess #20 will soon make this obsolete, but might as well have something working with Optim master until that merges...

**Comment by pkofod** [comment]
I hadn't seen this, but just for future reference `Optim.minimizer(results)` would have been a bit safer, as it has been in the package for a few tags, we just waited to change the fields, because some packages (like this) might still be calling `.minimum` directly.

**Pull request merged**
